// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protobuf/agent-backend/websocket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type K8SStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Namespace     []string               `protobuf:"bytes,2,rep,name=namespace,proto3" json:"namespace,omitempty"`
	ClusterName   string                 `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SStatus) Reset() {
	*x = K8SStatus{}
	mi := &file_protobuf_agent_backend_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SStatus) ProtoMessage() {}

func (x *K8SStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_backend_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SStatus.ProtoReflect.Descriptor instead.
func (*K8SStatus) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_backend_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *K8SStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *K8SStatus) GetNamespace() []string {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *K8SStatus) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

var File_protobuf_agent_backend_websocket_proto protoreflect.FileDescriptor

const file_protobuf_agent_backend_websocket_proto_rawDesc = "" +
	"\n" +
	"&protobuf/agent-backend/websocket.proto\x12\x03api\"f\n" +
	"\tK8sStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1c\n" +
	"\tnamespace\x18\x02 \x03(\tR\tnamespace\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterNameB\x06Z\x04./pbb\x06proto3"

var (
	file_protobuf_agent_backend_websocket_proto_rawDescOnce sync.Once
	file_protobuf_agent_backend_websocket_proto_rawDescData []byte
)

func file_protobuf_agent_backend_websocket_proto_rawDescGZIP() []byte {
	file_protobuf_agent_backend_websocket_proto_rawDescOnce.Do(func() {
		file_protobuf_agent_backend_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_agent_backend_websocket_proto_rawDesc), len(file_protobuf_agent_backend_websocket_proto_rawDesc)))
	})
	return file_protobuf_agent_backend_websocket_proto_rawDescData
}

var file_protobuf_agent_backend_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_agent_backend_websocket_proto_goTypes = []any{
	(*K8SStatus)(nil), // 0: api.K8sStatus
}
var file_protobuf_agent_backend_websocket_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_agent_backend_websocket_proto_init() }
func file_protobuf_agent_backend_websocket_proto_init() {
	if File_protobuf_agent_backend_websocket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_agent_backend_websocket_proto_rawDesc), len(file_protobuf_agent_backend_websocket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_agent_backend_websocket_proto_goTypes,
		DependencyIndexes: file_protobuf_agent_backend_websocket_proto_depIdxs,
		MessageInfos:      file_protobuf_agent_backend_websocket_proto_msgTypes,
	}.Build()
	File_protobuf_agent_backend_websocket_proto = out.File
	file_protobuf_agent_backend_websocket_proto_goTypes = nil
	file_protobuf_agent_backend_websocket_proto_depIdxs = nil
}
